### ISSUE TITLE
How to add card images

### ISSUE THREAD

**Issue by link-discord** [Pbatch/ClashRoyaleBuildABot#1]
Hello! I love this project but I would like to add more cards to the images so more cards can be used & recognized, such as the champion cards. Could you add the rest of the cards in the game or at least tell me how you got these images? Thanks

**Comment by Pbatch** [comment]
Hi there! Thanks for your support :) 

I've added the champion cards images and updated the CSV with their metadata. Originally I found the images in another repository, but for new images I just crop the portraits in the Wiki (https://clashroyale.fandom.com/wiki/Category:Champion_Cards).

Let me know if they work for your use case, and if there are any other cards that you think need adding.

**Comment by Pbatch** [comment]
@all-contributors please add @link-discord for data
