### ISSUE TITLE
problem in install

### ISSUE THREAD

**Issue by karimmnnasser** [Pbatch/ClashRoyaleBuildABot#101]
ERROR: Cannot install clashroyalebuildabot==1.0.0, clashroyalebuildabot==1.0.1, clashroyalebuildabot==1.1.0, clashroyalebuildabot==1.1.1, clashroyalebuildabot==1.1.2 and clashroyalebuildabot==1.2.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    clashroyalebuildabot 1.2.0 depends on onnxruntime
    clashroyalebuildabot 1.1.2 depends on onnxruntime
    clashroyalebuildabot 1.1.1 depends on onnxruntime
    clashroyalebuildabot 1.1.0 depends on onnxruntime
    clashroyalebuildabot 1.0.1 depends on onnxruntime
    clashroyalebuildabot 1.0.0 depends on onnxruntime

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by Pbatch** [comment]
I will have a look at this. For now, try using a separate venv

**Comment by Leviaria** [comment]
Better late than never — issue [#101](https://github.com/Pbatch/ClashRoyaleBuildABot/issues/101) resolved. 

**Enjoy ClashRoyaleBuildABot!**
