### ISSUE TITLE
setup problem

### ISSUE THREAD

**Issue by ZeddHp** [Pbatch/ClashRoyaleBuildABot#102]
Can somebody help?

I get this error when trying to run screen.py or main.py:
![image](https://github.com/Pbatch/ClashRoyaleBuildABot/assets/68005483/2b39f7b4-173a-403e-aec4-32b2d3a725bc)

py version - 3.8.10 

I have installed and started adb, installed all packages, disabled firewall, setup bluestacks

**Comment by Pbatch** [comment]
ADB is annoying. 

Have you found the discussion at https://github.com/Pbatch/ClashRoyaleBuildABot/issues/86? These guys had some ideas about to get it fixed it it's not working for you :)
