### ISSUE TITLE
File launch error screen.py

### ISSUE THREAD

**Issue by sheka00** [Pbatch/ClashRoyaleBuildABot#106]
I'm trying to run a file from different directories, namely the first run from a folder with an adb exe file, the second without it, slightly different errors pop up, initially I managed to run screen.py But something went wrong

I installed all the environment variables needed, all the library dependencies

![error1](https://github.com/Pbatch/ClashRoyaleBuildABot/assets/72471472/d9a00b5e-b284-4d4d-8f25-09850d808018)
![error2](https://github.com/Pbatch/ClashRoyaleBuildABot/assets/72471472/fd916955-5647-4b92-9616-eb87ea4d52b8)

**Comment by Leviaria** [comment]
The emulator typically establishes a connection automatically, so the command adb connect 127.0.0.1:5555 is not necessary to ensure a connection. You can use the adb devices command to verify if the emulator is connected.
