### ISSUE TITLE
Great project! Bot suggestions

### ISSUE THREAD

**Issue by neb0123** [Pbatch/ClashRoyaleBuildABot#11]
This is a fantastic project! Some bot ideas:
- Bridge spam
- Mirror opponents elixir costs
- Change placement dependant on opponent placement and tower health
- Reduce sample spaces of possible moves and/or apply approximate-KNN to chose a move

**Comment by wordpad25** [comment]
@Pbatch Could we train bot NN on top ladder replays?
It's a huge readily available dataset and replay syntax is already excellently minimalistic - only timestamp, unit played and coordinates. 

Additionally, ideal play in any situation is going to be very consistent, so even a single replay would be enough to learn correct response to opponent play for those situations.

**Comment by Pbatch** [comment]
Wow I didn't even realize replays existed! I'm assuming you're talking about these: https://royaleapi.com/decks/ranked

Do you know if there's a nice way to download the output? 

It is the most promising way I've seen so far to response to enemies.

**Comment by wordpad25** [comment]
> Do you know if there's a nice way to download the output?

Yes, there is. Do you have a discord?

**Comment by candlelightner** [comment]
Have you managed to download some data? I yes, how large is your dataset?

**Comment by Pbatch** [comment]
@wordpad25 PBatch#6429 is my Discord. @candlelightner we are working on it! No data yet :)

**Comment by candlelightner** [comment]
> @wordpad25 PBatch#6429 is my Discord. @candlelightner we are working on it! No data yet :)

I might be able to help out.

**Comment by wordpad25** [comment]
@candlelightner awesome work! could you share your discord, so we could
collaborate on this?
I will share my dataset.

**Comment by candlelightner** [comment]
I sent you a request.

**Comment by wordpad25** [comment]
my discord is igor_#5314

**Comment by Noahhw46** [comment]
Do you guys have a dataset yet? I've been working on a model and (probably) have access to GPUs. Let me know - I can share my discord.

**Comment by candlelightner** [comment]
Share your discord with me if you don't already have the dataset.

**Comment by Noahhw46** [comment]
Totally lost track of this at some point. But I'm still interested - discord is noahhw46#6161

**Comment by clashai** [comment]
> Share your discord with me if you don't already have the dataset.

gala#3520 my discord i have high end gpus for training and ready to help

**Comment by alex-pelaez** [comment]
> @wordpad25 PBatch#6429 is my Discord. @candlelightner we are working on it! No data yet :)

Hello, I am inerested on the replay data becasue. Did you make any progress?

**Comment by candlelightner** [comment]
> > @wordpad25 PBatch#6429 is my Discord. @candlelightner we are working on it! No data yet :)
> 
> Hello, I am interested on the replay data. Did you make any progress?

No, I failed at sending the inputs to the game.
