### ISSUE TITLE
Set Up Probleem

### ISSUE THREAD

**Issue by Longzai-cql** [Pbatch/ClashRoyaleBuildABot#110]
Hello, I Just tried to setup a bot. I followed your steps. I got a screenshot successfully but when I try running example/main.py, it shows

Traceback (most recent call last):
  File "F:\Royal\ClashRoyaleBuildABot-1.2.1\example\main.py", line 4, in <module>
    from custom_bot import CustomBot # see custom_bot.py
  File "F:\Royal\ClashRoyaleBuildABot-1.2.1\example\custom_bot.py", line 9, in <module>
    from clashroyalebuildabot.bot import Bot
ModuleNotFoundError: No module named 'clashroyalebuildabot'

![Uploading Snipaste_2024-03-03_21-58-07.png…]()

**Comment by Leviaria** [comment]
The error "ModuleNotFoundError: No module named 'clashroyalebuildabot'" means that Python cannot find the clashroyalebuildabot module. f you're running the main.py file from a different directory than where the clashroyalebuildabot module is located, Python won't be able to find it. Make sure your working directory is set to the root of the project.

ClashRoyaleBuildABot/
├── clashroyalebuildabot/
│   ├── __init__.py
│   ├── bot.py
│   ├── data/
│   │   ├── constants.py
│   │   └── ├── ... other data files
│   ├── detector/
│   │   ├── ├── ... detector files
│   ├── models/
│   │   ├── ├── ... model files
│   ├── utils/
│   │   ├── ├── ... utility files
├── example/
│   ├── main.py
│   ├── custom_bot.py
│   ├── custom_action.py
│   └── ├── ... other example files
├── README.md
├── requirements.txt
├── setup.py
└── ├── ... other project files
