### ISSUE TITLE
New Feature?

### ISSUE THREAD

**Issue by Leviaria** [Pbatch/ClashRoyaleBuildABot#119]
I've implemented a new live-preview interface as a debug feature - I removed the menu again to keep the functionalities consistent. What do you think about it? I'd be happy to incorporate it into the source code here as well. Unfortunately, my PC isn't the fastest, but otherwise, it works with a 1-second delay.

![Update-ezgif com-optimize (1)](https://github.com/Leviaria/ClashRoyaleBuildABotMod/assets/113382526/24125d70-a821-465f-9811-fc5846eaeb9f)

**Comment by Pbatch** [comment]
Oh nice that's super cool. Let's get it integrated and we can worry about optimizing it later.

Is there anything you need from me to help the bot run on your PC? I.e. I can prune the ONNX models to make them faster.

**Comment by Pbatch** [comment]
I tried only a variant of this today to make 5000 synthetic images. You can see the results here: https://github.com/Pbatch/ClashRoyaleBuildABot/wiki/State

I will try a super run with all the classes in the game at some point. Let me know if you want to the see the code!
