### ISSUE TITLE
Consolidated Threads Instead of Multiple Issue Reports

### ISSUE THREAD

**Issue by Leviaria** [Pbatch/ClashRoyaleBuildABot#129]
Wouldn't it be smarter to create three threads (suggestions, problems, general talk) instead of letting everyone open issue threads that end up abandoned? It would be cleaner and more organized. Also, please add me on Discord because you released something earlier that I was just working on. To avoid such overlaps in the future, we could stay in touch if you’d like. :)

**Comment by Pbatch** [comment]
https://discord.gg/EK4y8YVd

**Comment by Pbatch** [comment]
Imo GitHub is best only for Issues. A Discord server is a much better way to get people collaborating :)
