### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by nikita9091239** [Pbatch/ClashRoyaleBuildABot#132]
C:\Games\ClashRoyaleBuildABot>example\main.py
Traceback (most recent call last):
  File "C:\Games\ClashRoyaleBuildABot\example\main.py", line 5, in <module>
    from clashroyalebuildabot.data.cards import Cards
ModuleNotFoundError: No module named 'clashroyalebuildabot.data.cards'
![image](https://github.com/Pbatch/ClashRoyaleBuildABot/assets/83181206/bc1b3dee-69e0-472c-8ec6-30a75a83b26d)
![image](https://github.com/Pbatch/ClashRoyaleBuildABot/assets/83181206/4531e895-c995-4029-9ef2-0e6d19cbd875)

**Comment by Pbatch** [comment]
@all-contributors please add @nikita9091239 for a bug report
