### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by camillo1990** [Pbatch/ClashRoyaleBuildABot#14]
Pls help (

Torch module installed

Traceback (most recent call last):
  File "C:\Users\User\Desktop\Новая папка\ClashRoyaleBuildABot\main.py", line 1, in <module>
    from src.bot.pete.pete_bot import PeteBot
  File "C:\Users\User\Desktop\Новая папка\ClashRoyaleBuildABot\src\bot\pete\pete_bot.py", line 4, in <module>
    from src.bot.bot import Bot
  File "C:\Users\User\Desktop\Новая папка\ClashRoyaleBuildABot\src\bot\bot.py", line 20, in <module>
    from src.state.detector import Detector
  File "C:\Users\User\Desktop\Новая папка\ClashRoyaleBuildABot\src\state\detector.py", line 6, in <module>
    from src.state.number_detector import NumberDetector
  File "C:\Users\User\Desktop\Новая папка\ClashRoyaleBuildABot\src\state\number_detector.py", line 6, in <module>
    from src.state.onnx_detector import OnnxDetector
  File "C:\Users\User\Desktop\Новая папка\ClashRoyaleBuildABot\src\state\onnx_detector.py", line 2, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by GavriloviciEduard** [comment]
Have a look [here](https://github.com/Pbatch/ClashRoyaleBuildABot/wiki/Setup). Make sure to install needed python dependencies.

**Comment by camillo1990** [comment]
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime

**Comment by camillo1990** [comment]
:{

**Comment by camillo1990** [comment]
> 
can you help me? The error occurs when you enter the command pip install -r requirements.txt

**Comment by GavriloviciEduard** [comment]
Install python 3.9 because that's the last version supported by onnxruntime.

**Comment by camillo1990** [comment]
> Install python 3.9 because that's the newest version supported by onnxruntime.

New error :{

  Using cached pywin32-302-cp39-cp39-win32.whl (8.5 MB)
ERROR: Cannot install -r requirements.txt (line 7) because these package versions have conflicting dependencies.

The conflict is caused by:
    torchvision 0.2.2.post3 depends on torch
    torchvision 0.2.2.post2 depends on torch
    torchvision 0.2.2 depends on torch
    torchvision 0.2.1 depends on torch
    torchvision 0.2.0 depends on torch
    torchvision 0.1.9 depends on torch
    torchvision 0.1.8 depends on torch
    torchvision 0.1.7 depends on torch

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by GavriloviciEduard** [comment]
Try the following: 
1. python -m pip uninstall -r requirements.txt
2. python -m pip install -r requirements.txt

**Comment by camillo1990** [comment]
This message is displayed and nothing happens. Thanks in advance ^-^





Requirement already satisfied: pywin32 in c:\users\user\appdata\local\programs\python\python39-32\lib\site-packages (from -r requirements.txt (line 1)) (303)
Requirement already satisfied: Pillow in c:\users\user\appdata\local\programs\python\python39-32\lib\site-packages (from -r requirements.txt (line 2)) (9.0.1)
Requirement already satisfied: numpy in c:\users\user\appdata\local\programs\python\python39-32\lib\site-packages (from -r requirements.txt (line 3)) (1.22.2)
Requirement already satisfied: onnxruntime in c:\users\user\appdata\local\programs\python\python39-32\lib\site-packages (from -r requirements.txt (line 4)) (1.10.0)
Requirement already satisfied: imagehash in c:\users\user\appdata\local\programs\python\python39-32\lib\site-packages (from -r requirements.txt (line 5)) (4.2.1)
Requirement already satisfied: mss in c:\users\user\appdata\local\programs\python\python39-32\lib\site-packages (from -r requirements.txt (line 6)) (6.1.0)
Requirement already satisfied: torchvision in c:\users\user\appdata\local\programs\python\python39-32\lib\site-packages (from -r requirements.txt (line 7)) (0.1.6)
Requirement already satisfied: protobuf in c:\users\user\appdata\local\programs\python\python39-32\lib\site-packages (from onnxruntime->-r requirements.txt (line 4)) (3.19.4)
Requirement already satisfied: flatbuffers in c:\users\user\appdata\local\programs\python\python39-32\lib\site-packages (from onnxruntime->-r requirements.txt (line 4)) (2.0)
Requirement already satisfied: six in c:\users\user\appdata\local\programs\python\python39-32\lib\site-packages (from imagehash->-r requirements.txt (line 5)) (1.16.0)
Requirement already satisfied: scipy in c:\users\user\appdata\local\programs\python\python39-32\lib\site-packages (from imagehash->-r requirements.txt (line 5)) (1.8.0)
Requirement already satisfied: PyWavelets in c:\users\user\appdata\local\programs\python\python39-32\lib\site-packages (from imagehash->-r requirements.txt (line 5)) (1.2.0)

**Comment by camillo1990** [comment]
not work

**Comment by Pbatch** [comment]
I'm working on removing the torch and torchvision dependencies; give me a day or two. Hopefully everything should work much easier then :) Thank you for your patience.

**Comment by Pbatch** [comment]
Hello! Sorry it has been a while, I've been very busy. The code doesn't need a specific version of Python anymore (I don't think...), as torch (and torchvision) are no longer dependencies.

If you have any further problems please post them below, but I believe your problem should be fixed now :)
