### ISSUE TITLE
What version of python has to be installed?

### ISSUE THREAD

**Issue by Emgimeer-Bazder** [Pbatch/ClashRoyaleBuildABot#2]
Hey, noob here.
What version of python needs to be installed? 
How could I have figured this out on my own?

I'm having issues installing onnxruntime, I think it's my python version.

**Comment by Emgimeer-Bazder** [comment]
Solved.
Python 3.9 works.

**Comment by Pbatch** [comment]
@all-contributors please add @Emgimeer-Bazder for fixing a bug
