### ISSUE TITLE
error when installing the requirement

### ISSUE THREAD

**Issue by Nyantad** [Pbatch/ClashRoyaleBuildABot#20]
![image](https://user-images.githubusercontent.com/68382673/160202933-6bfd153e-d312-4704-95c5-031ca4f33b33.png)

i have this when i put the command :    pip install -r requirements.txt
can i get some help ?

**Comment by Nyantad** [comment]
ok I found it, it's just that onnxruntime doesn't support python 3.10.X

**Comment by Pbatch** [comment]
https://github.com/all-contributors please add @Nyantad for bug.

**Comment by Pbatch** [comment]
@all-contributors please add @Nyantad for bug.

**Comment by Pbatch** [comment]
I looked on the ONNX website and it says only Python 3.6 - 3.9 are supported. Thanks for your help.
