### ISSUE TITLE
Suggestion: Live visualizer

### ISSUE THREAD

**Issue by EnderBenjy** [Pbatch/ClashRoyaleBuildABot#206]
Similar to what the debugger does, but live (and that does not save the images).
I made a very simple one using opencv based on the debugger functions, I can send a PR if it's useful.
![image](https://i.imgur.com/O72WxnV.png)

**Comment by Pbatch** [comment]
This is epic. Let's get this into main :)

**Comment by Pbatch** [comment]
Good job :)
