### ISSUE TITLE
Having a tile map would be super helpful.

### ISSUE THREAD

**Issue by OwenKruse** [Pbatch/ClashRoyaleBuildABot#28]
The title says most of it. I find it super difficult to place my troop where I want them to go because I have to trial and error where the tile that I want to place it at is located. Even a google sheets table would be super helpful. Love the project and I'm excited to see what people are able to do with it.

**Comment by Pbatch** [comment]
Thanks for your support. 

If you use this function it can convert from the discrete coordinates to the location to click.
```python
@staticmethod
def _get_tile_centre(tile_x, tile_y):
    """
    Get the (x, y) coordinate of the centre of a tile
    """
    x = TILE_INIT_X + (tile_x + 0.5) * TILE_WIDTH
    y = DISPLAY_HEIGHT - TILE_INIT_Y - (tile_y + 0.5) * TILE_HEIGHT
    return x, y
```

I've made a tile map for you so that you can find `tile_x` and `tile_y` easier. 
![image](https://user-images.githubusercontent.com/37177749/170821564-8811b6e4-74e0-4f6c-a6b6-6be3ff61fc4e.png)

Let me know if this helps solve your problem :)

**Comment by Pbatch** [comment]
https://github.com/all-contributors please add @OwenKruse for improving the documentation.

**Comment by Pbatch** [comment]
@all-contributos please add @OwenKruse for helping out with documentation.

**Comment by Pbatch** [comment]
@all-contributors please add @OwenKruse for helping out with documentation.

**Comment by OwenKruse** [comment]
Awesome thank you! I have made a bot that attempts to play 2.6 hog cycle and I would love to share it with others. Should I make a pull request or is there somewhere I can share too?

**Comment by Pbatch** [comment]
Oooh, great stuff :) Yes, make a pull request, and I'll add something in the README and the documentation too.

If are you feeling really ambitious, try turning on debug mode to generate a folder of screenshots. Then if you send me those (through Google Drive or something) I can make a GIF of your bot in action.
