### ISSUE TITLE
NoneType AttributeError on device.screencap in screen.py

### ISSUE THREAD

**Issue by marmig0404** [Pbatch/ClashRoyaleBuildABot#39]
did: pip install --force-reinstall --no-cache-dir ClashRoyaleBuildABot==1.0.1
installed everything perfectly fine.
then did: 
> python main.py

diff error this time:
> python main.py
> Traceback (most recent call last):
>   File "C:\Users\SP\Downloads\ClashRoyaleBuildABot-main\ClashRoyaleBuildABot-main\example\main.py", line 18, in <module>
>     main()
>   File "C:\Users\SP\Downloads\ClashRoyaleBuildABot-main\ClashRoyaleBuildABot-main\example\main.py", line 14, in main
>     bot.run()
>   File "C:\Users\SP\Downloads\ClashRoyaleBuildABot-main\ClashRoyaleBuildABot-main\example\custom_bot.py", line 40, in run
>     self.set_state()
>   File "C:\Users\SP\AppData\Local\Programs\Python\Python39\lib\site-packages\clashroyalebuildabot\bot\bot.py", line 101, in set_state
>     screenshot = self.screen.take_screenshot()
>   File "C:\Users\SP\AppData\Local\Programs\Python\Python39\lib\site-packages\clashroyalebuildabot\screen.py", line 19, in take_screenshot
>     screenshot = self.device.screencap()
> AttributeError: 'NoneType' object has no attribute 'screencap'

_Originally posted by @gl4d in https://github.com/Pbatch/ClashRoyaleBuildABot/issues/37#issuecomment-1169367664_

**Comment by marmig0404** [comment]
@Pbatch 
Not detecting emulator device possibly?

**Comment by gl4d** [comment]
adb is running.
Android debug bridge in bluestack is on. @:5555
bluestack's resolution set to 720x1280

any idea of what could be wrong?

**Comment by Pbatch** [comment]
This is an issue with the device not being detected.

Try
```
adb kill-server
adb start-server
```
with Bluestacks open

**Comment by gl4d** [comment]
did:

> adb kill-server
> adb start-server

1st time it didn't work.
restarted vm
did again: didn't work.
restarted again
3rd time: worked.

idk, it works now for w/e reasons.
thanks for your time.

**Comment by Pbatch** [comment]
No problem. I have had this issue before too! I might add something to the documentation to warn people.
