### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by sinamkh** [Pbatch/ClashRoyaleBuildABot#48]
I'm actually don't know about this pip and other stuff I need help I installed the python and click on the setup in the file but that doesn't have any respond......its 3.7 v

**Comment by Pbatch** [comment]
pip comes with Python so you should be OK on that front. Python 3.7 is OK too.

Have you tried following the steps in the Wiki? https://github.com/Pbatch/ClashRoyaleBuildABot/wiki/Setup

If you post some screenshots or logs of your error output I will be in a better position to help you out.

**Comment by sinamkh** [comment]
![Screenshot 2022-08-26 015407](https://user-images.githubusercontent.com/111743832/186772202-f90323c9-2584-494d-88c1-c42ddbdb08a5.png)

**Comment by sinamkh** [comment]
https://user-images.githubusercontent.com/111743832/186772301-194b51b4-445d-4289-84e2-97bfafae8af2.mp4

**Comment by sinamkh** [comment]
https://user-images.githubusercontent.com/111743832/186772536-28e3ae39-bc56-441d-a146-563e23b10712.mp4

**Comment by sinamkh** [comment]
in video i click on setup but nothing happen

**Comment by sinamkh** [comment]
Uploading bandicam 2022-08-26 02-03-21-142.mp4…

**Comment by sinamkh** [comment]
https://user-images.githubusercontent.com/111743832/186773025-6c2cc1e1-de84-43eb-ba17-aee2a498278c.mp4

**Comment by marmig0404** [comment]
try running the setup file in the windows command prompt  using `python setup.py`
please share the result here.

**Comment by marmig0404** [comment]
Also, I would refer to [the wiki](https://github.com/Pbatch/ClashRoyaleBuildABot/wiki/Setup) for help on installing this package for use. it shows a concise install procedure which I've found works on many systems.

**Comment by sinamkh** [comment]
> try running the setup file in the windows command prompt using `python setup.py install` please share the result here.

C:\Users\omid>python setup.py
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by sinamkh** [comment]
> try running the setup file in the windows command prompt using `python setup.py install` please share the result here.
C:\Users\omid>python setup.py install
python: can't open file 'setup.py': [Errno 2] No such file or directory

**Comment by sinamkh** [comment]
> try running the setup file in the windows command prompt using `python setup.py install` please share the result here.

C:\Users\omid>python setup.py install
python: can't open file 'setup.py': [Errno 2] No such file or directory

**Comment by marmig0404** [comment]
> C:\Users\omid>python setup.py install
> 
> python: can't open file 'setup.py': [Errno 2] No such file or directory

Python can't find the setup.py file because you're not in the right directory.

Ensure your current directory is the repository's directory, that which you have downloaded, then run the above command.

**Comment by sinamkh** [comment]
i dont know what is repository's directory...this is some kind of cloud shit how can use that with cmd code
 i upload the files in github and this is cant be more 100 mg 
this is impossible with my knowledge do this shit

**Comment by sinamkh** [comment]
i cant understand this actually 
if u can record a video for this 
so grateful

**Comment by marmig0404** [comment]
you can follow the instructions on the wiki for setup and install.



if that isn't your flavor, i've laid out precise commands for you to run which will guarantee an install and run the included example.

in the command prompt type these commands one after the other.

```
winget install -e --id Python.Python.3 #installing latest python 3 version

winget install -e --id Git.Git #installing git

git clone https://github.com/Pbatch/ClashRoyaleBuildABot.git #cloning the repository

cd ClashRoyaleBuildABot #change directory to repo

python setup.py install #install the package from source

python example/main.py #run the example code included in source
```

**Comment by Pbatch** [comment]
@all-contributors please add @marmig0404 for helping new members of the community get the code running.

**Comment by sinamkh** [comment]
icrosoft Windows [Version 10.0.19044.1165]
(c) Microsoft Corporation. All rights reserved.

C:\Users\omid>winget install -e --id Python.Python.3 #installing latest python 3 version
Windows Package Manager v1.3.2091
Copyright (c) Microsoft Corporation. All rights reserved.

Found a positional argument when none was expected : 'latest'

Installs the selected package, either found by searching a configured source or directly from a manifest. By default, the query must case-insensitively match the id, name, or moniker of the package. Other fields can be used by passing their appropriate option.

usage: winget install [[-q] <query>] [<options>]

The following arguments are available:
  -q,--query                   The query used to search for a package

The following options are available:
  -m,--manifest                The path to the manifest of the package
  --id                         Filter results by id
  --name                       Filter results by name
  --moniker                    Filter results by moniker
  -v,--version                 Use the specified version; default is the latest version
  -s,--source                  Find package using the specified source
  --scope                      Select install scope (user or machine)
  -a,--architecture            Select the architecture to install
  -e,--exact                   Find package using exact match
  -i,--interactive             Request interactive installation; user input may be needed
  -h,--silent                  Request silent installation
  --locale                     Locale to use (BCP47 format)
  -o,--log                     Log location (if supported)
  --override                   Override arguments to be passed on to the installer
  -l,--location                Location to install to (if supported)
  --force                      Override the installer hash check
  --dependency-source          Find package dependencies using the specified source
  --accept-package-agreements  Accept all license agreements for packages
  --header                     Optional Windows-Package-Manager REST source HTTP header
  --accept-source-agreements   Accept all source agreements during source operations
  -r,--rename                  The value to rename the executable file (portable)

More help can be found at: https://aka.ms/winget-command-install

C:\Users\omid>
C:\Users\omid>winget install -e --id Git.Git #installing git
Windows Package Manager v1.3.2091
Copyright (c) Microsoft Corporation. All rights reserved.

Found a positional argument when none was expected : 'git'

Installs the selected package, either found by searching a configured source or directly from a manifest. By default, the query must case-insensitively match the id, name, or moniker of the package. Other fields can be used by passing their appropriate option.

usage: winget install [[-q] <query>] [<options>]

The following arguments are available:
  -q,--query                   The query used to search for a package

The following options are available:
  -m,--manifest                The path to the manifest of the package
  --id                         Filter results by id
  --name                       Filter results by name
  --moniker                    Filter results by moniker
  -v,--version                 Use the specified version; default is the latest version
  -s,--source                  Find package using the specified source
  --scope                      Select install scope (user or machine)
  -a,--architecture            Select the architecture to install
  -e,--exact                   Find package using exact match
  -i,--interactive             Request interactive installation; user input may be needed
  -h,--silent                  Request silent installation
  --locale                     Locale to use (BCP47 format)
  -o,--log                     Log location (if supported)
  --override                   Override arguments to be passed on to the installer
  -l,--location                Location to install to (if supported)
  --force                      Override the installer hash check
  --dependency-source          Find package dependencies using the specified source
  --accept-package-agreements  Accept all license agreements for packages
  --header                     Optional Windows-Package-Manager REST source HTTP header
  --accept-source-agreements   Accept all source agreements during source operations
  -r,--rename                  The value to rename the executable file (portable)

More help can be found at: https://aka.ms/winget-command-install

C:\Users\omid>
C:\Users\omid>git clone https://github.com/Pbatch/ClashRoyaleBuildABot.git #cloning the repository
'git' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\omid>
C:\Users\omid>cd ClashRoyaleBuildABot #change directory to repo
The system cannot find the path specified.

C:\Users\omid>
C:\Users\omid>python setup.py install #install the package from source
python: can't open file 'C:\Users\omid\setup.py': [Errno 2] No such file or directory

C:\Users\omid>
C:\Users\omid>python example/main.py #run the example code included in source

**Comment by sinamkh** [comment]
this is what happen

**Comment by sinamkh** [comment]
Microsoft Windows [Version 10.0.19044.1165]
(c) Microsoft Corporation. All rights reserved.

C:\Users\omid>winget install -e --id Python.Python.3 #installing latest python 3 version
Windows Package Manager v1.3.2091
Copyright (c) Microsoft Corporation. All rights reserved.

Found a positional argument when none was expected : 'latest'

Installs the selected package, either found by searching a configured source or directly from a manifest. By default, the query must case-insensitively match the id, name, or moniker of the package. Other fields can be used by passing their appropriate option.

usage: winget install [[-q] <query>] [<options>]

The following arguments are available:
  -q,--query                   The query used to search for a package

The following options are available:
  -m,--manifest                The path to the manifest of the package
  --id                         Filter results by id
  --name                       Filter results by name
  --moniker                    Filter results by moniker
  -v,--version                 Use the specified version; default is the latest version
  -s,--source                  Find package using the specified source
  --scope                      Select install scope (user or machine)
  -a,--architecture            Select the architecture to install
  -e,--exact                   Find package using exact match
  -i,--interactive             Request interactive installation; user input may be needed
  -h,--silent                  Request silent installation
  --locale                     Locale to use (BCP47 format)
  -o,--log                     Log location (if supported)
  --override                   Override arguments to be passed on to the installer
  -l,--location                Location to install to (if supported)
  --force                      Override the installer hash check
  --dependency-source          Find package dependencies using the specified source
  --accept-package-agreements  Accept all license agreements for packages
  --header                     Optional Windows-Package-Manager REST source HTTP header
  --accept-source-agreements   Accept all source agreements during source operations
  -r,--rename                  The value to rename the executable file (portable)

More help can be found at: https://aka.ms/winget-command-install

C:\Users\omid>winget install -e --id Git.Git #installing git
Windows Package Manager v1.3.2091
Copyright (c) Microsoft Corporation. All rights reserved.

Found a positional argument when none was expected : 'git'

Installs the selected package, either found by searching a configured source or directly from a manifest. By default, the query must case-insensitively match the id, name, or moniker of the package. Other fields can be used by passing their appropriate option.

usage: winget install [[-q] <query>] [<options>]

The following arguments are available:
  -q,--query                   The query used to search for a package

The following options are available:
  -m,--manifest                The path to the manifest of the package
  --id                         Filter results by id
  --name                       Filter results by name
  --moniker                    Filter results by moniker
  -v,--version                 Use the specified version; default is the latest version
  -s,--source                  Find package using the specified source
  --scope                      Select install scope (user or machine)
  -a,--architecture            Select the architecture to install
  -e,--exact                   Find package using exact match
  -i,--interactive             Request interactive installation; user input may be needed
  -h,--silent                  Request silent installation
  --locale                     Locale to use (BCP47 format)
  -o,--log                     Log location (if supported)
  --override                   Override arguments to be passed on to the installer
  -l,--location                Location to install to (if supported)
  --force                      Override the installer hash check
  --dependency-source          Find package dependencies using the specified source
  --accept-package-agreements  Accept all license agreements for packages
  --header                     Optional Windows-Package-Manager REST source HTTP header
  --accept-source-agreements   Accept all source agreements during source operations
  -r,--rename                  The value to rename the executable file (portable)

More help can be found at: https://aka.ms/winget-command-install

C:\Users\omid>git clone https://github.com/Pbatch/ClashRoyaleBuildABot.git #cloning the repository
'git' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\omid>cd ClashRoyaleBuildABot #change directory to repo
The system cannot find the path specified.

C:\Users\omid>python setup.py install #install the package from source
python: can't open file 'C:\Users\omid\setup.py': [Errno 2] No such file or directory

C:\Users\omid>python example/main.py #run the example code included in source
python: can't open file 'C:\Users\omid\example\main.py': [Errno 2] No such file or directory

**Comment by sinamkh** [comment]
i tried that again and same result

**Comment by marmig0404** [comment]
> i tried that again and same result 
> 
> 

just use the pip install command in the wiki

**Comment by sinamkh** [comment]
nice something is happen

**Comment by marmig0404** [comment]
resolution reached, please close :) @Pbatch
