### ISSUE TITLE
Not dropping cards in battlefield

### ISSUE THREAD

**Issue by LiinxTV** [Pbatch/ClashRoyaleBuildABot#57]
Hi,

I have setup everything, connection to adb, screenshot is also good, but the botis not taking card, it always says "please choose a card"

How to solve this ?

I also changed bluestacks screen resolution as in the setup tutorial.

**Comment by LiinxTV** [comment]
Also, i don't have drawings, is it normal or you must activate or call smth ?

**Comment by Pbatch** [comment]
You should get screenshots in `clashroyalebuildabot/screenshots`  if you add the `debug=True` flag:
```python
bot = CustomBot(card_names, debug=True)
```

They look like this by default:
![image](https://user-images.githubusercontent.com/37177749/209330417-e105cf52-b8fb-4f21-86a6-bf352a4b5d46.png)

What are your screenshots looking like? If it says "please choose a card" it's normally misclicking.

How did you install the library? At the moment the version of the code from pip is not up-to-date, so you might have better luck with `git clone`.
