### ISSUE TITLE
Unable to start game with the example bot

### ISSUE THREAD

**Issue by BassCoder2808** [Pbatch/ClashRoyaleBuildABot#58]
Hi @Pbatch , I have cloned the repo and was trying to start a example bot as per instructions in the settings section in wiki after setting up the project. But whenever I try to use the example bot it gives error. I have attached the error msg to this post.
![image](https://user-images.githubusercontent.com/65075935/212970421-3b8630e2-5e6e-4359-9876-8989dcb98a57.png)
But at the same time when I run the screenshot file, it is able to generate the screenshot, 
![screen](https://user-images.githubusercontent.com/65075935/212970820-d009c61d-6909-47dd-ac71-7cf2ffaf5f6f.jpg)

**Comment by Pbatch** [comment]
Hello! This is my bad, the pip version of the library is out-of-date, but I've made a new release now.

Can you try:
```
pip install --upgrade --force-reinstall ClashRoyaleBuildABot
```

Let me know if it's still playing up after that :)

**Comment by BassCoder2808** [comment]
Thanks @Pbatch , yes by running the above command, it has started working now

**Comment by Pbatch** [comment]
@all-contributors please add @BassCoder2808 for bug report
