### ISSUE TITLE
Rename hungry_dragon to baby_dragon & Rename minipekka to mini_pekka

### ISSUE THREAD

**Issue by Chi-EEE** [Pbatch/ClashRoyaleBuildABot#61]
### Baby Dragon:
Rename `hungry_dragon` to `baby_dragon`:

- In the characters.csv, it is listed as `baby_dragon`
- Easier to write

### Mini Pekka:
Rename `minipekka` to `mini_pekka`:

- ~~In the characters.csv, it is listed as `mini_pekka`~~
- It has a space and it is the only card with two words that does not have a space

### Where to change:

- In the code where the values appear
- In the Wiki
- CSV
- Image Name

[characters.csv](https://github.com/smlbiobot/cr-csv/blob/master/assets/csv_logic/characters.csv)

**Comment by Pbatch** [comment]
I am hesitant to do this atm because I would also have to change these names in various data sets and config files that I have outside of the repo.
