### ISSUE TITLE
About how to set new Screen IDs in constants.SCREEN_CONFIG[XX].bbox

### ISSUE THREAD

**Issue by gogit2194** [Pbatch/ClashRoyaleBuildABot#66]
HI! This is a awesome project! 
However, there some SCREEN_CONFIG.bbox settings rule of constants makes me so confuse, such as why OK_bbox setting is like `OK_X = 143, OK_Y = 558` ,even ok button's upper left coordinates is (280,1096) approximately.
How to get them?
And I want to add “Party mode” icon in SCREEN_CONFIG for setting a new screen_state, I already screenshot a Party mode png-24 (without Alpha channel), and bbox setting using its upper left coordinates, but I still can not get a low hash_diffs like other state, end_of_game or lobby, down blow 10.  Could you please tell me how to set appropriate bbox values?

Here is my party setting in constants:
ClashRoyaleBuildABot\clashroyalebuildabot\data\images\screen\
party.png 38X38  24-PNG

![party](https://user-images.githubusercontent.com/23632372/217578752-e06ad24a-fb0a-464d-92ba-fc13ba71ece6.png)

```
PARTY_SIZE = 38
PARTY_X = 305
PARTY_Y = 397

SCREEN_CONFIG = {
.....
    'party': {'bbox': (PARTY_X,
                       PARTY_Y,
                       PARTY_X + PARTY_SIZE,
                       PARTY_Y + PARTY_SIZE),
              'click_coordinates': (420, 420)},
}

**Comment by Pbatch** [comment]
Hello! Sorry for the slow reply.

The bounding box values need to be scaled relative to the screenshot size. These scaling factors are `S_x = SCREENSHOT_WIDTH / DISPLAY_WIDTH = 368 / 720 = 0.51` and `S_y = SCREENSHOT_HEIGHT / DISPLAY_HEIGHT = 652 / 1280 = 0.51`. That explains why the coordinates are about 2x the size.

If you still have a problem with the hashes after this let me know and I will investigate. It's possible you might have to increase the threshold in `clashroyalebuildabot/state/screen_detector.py`...

**Comment by gogit2194** [comment]
The solution worked perfectly.
Thank you so much for your help, and really appreciate your time and effort in answering my question.
Then I found out that most of the min_hash of Party battle scenes is above 29. 
What needs to be solved now is to find an area of the image that can make the hash lower than 20 or even 10
