### ISSUE TITLE
Turn this into a Deck Tracker - Suggestion

### ISSUE THREAD

**Issue by warklp** [Pbatch/ClashRoyaleBuildABot#67]
Great project guys! 
Is there a way to turn this into a card tracker to know your oponnent cycle and make it work with champions too?
I think thats the better way to have a tool that really helps players

**Comment by Leviaria** [comment]
Card Tracker would only be useful if we leave out the botting aspect, but it can definitely be considered as a separate project in the future – it's definitely noted.
