### ISSUE TITLE
[Help Wanted] Stuck at setup

### ISSUE THREAD

**Issue by RazerRz** [Pbatch/ClashRoyaleBuildABot#69]
Hi, sorry for my noob question. I need help. I've completed the setup till here.

**_"If successful you should get this message:
connected to 127.0.0.1:<PORT>"_**

After that I'm lost. I try this but nothing happens.

**_"To check that the connection is working try taking a screenshot:
python clashroyalebuildabot/screen.py"_**

![image](https://user-images.githubusercontent.com/128511638/226686589-dd2c7545-feb4-4441-9712-c2bd3c00a158.png)

Do you have any video to show how to setup and create Bots. Thanks

**Comment by Pbatch** [comment]
The ```python clashroyalebuildabot/screen.py``` saves a screenshot to ```screenshot.jpg``` locally. Can you see that file?
If it didn't crash, normally it means everything is working fine.

Have you tried to run the example? I think you are very close to getting everything working!

**Comment by Pbatch** [comment]
You can provide a score function in `clashroyalebuildabot/example/custom_action.py` to help you do this.

You will want something along the lines of this
```python
def calculate_score(self, state):
    valid_tiles = [[6, 10], [7, 10]] # Whatever tiles you want
    tile = [self.tile_x, self.tile_y]
    if tile in valid_tiles:
        score = [np.random.random()]
    else:
        score = [0]
    return score
 ```

**Comment by RazerRz** [comment]
How do I do it... sorry for noob question.

**Comment by Pbatch** [comment]
If you want to change the behaviour of the minipekka say, then rewrite the corresponding function

I.e.
```python
def _calculate_minipekka_score(self, state):
    valid_tiles = [[6, 10], [7, 10]] # Whatever tiles you want
    tile = [self.tile_x, self.tile_y]
    if tile in valid_tiles:
        score = [np.random.random()]
    else:
        score = [0]
    return score
```

**Comment by RazerRz** [comment]
You mean replace this

def _calculate_minipekka_score(self, state):
        """
        Place minipekka on the bridge as high up as possible
        Try to target the lowest hp tower
        """
        left_hp, right_hp = [state['numbers'][f'{direction}_enemy_princess_hp']['number']
                             for direction in ['left', 'right']]
        score = [0]
        if self.tile_x == 3:
            score = [1, self.tile_y, left_hp != -1, left_hp <= right_hp]
        elif self.tile_x == 14:
            score = [1, self.tile_y, right_hp != -1, right_hp <= left_hp]
        return score

to this

def _calculate_minipekka_score(self, state):
    valid_tiles = [[6, 10], [7, 10]] # Whatever tiles you want
    tile = [self.tile_x, self.tile_y]
    if tile in valid_tiles:
        score = [np.random.random()]
    else:
        score = [0]
    return score
