### ISSUE TITLE
Bot doesn't work properly

### ISSUE THREAD

**Issue by reddythedev** [Pbatch/ClashRoyaleBuildABot#72]
After I start the bot, it doesn't do anything with no errors. My ADB is connected on port 5555 (Bluestacks).

**Comment by reddythedev** [comment]
Actually, started getting an error when running python3 example/main.py: subprocess.CalledProcessError: Command '['adb', 'shell', 'wm', 'size']' returned non-zero exit status 1.

**Comment by Pbatch** [comment]
This typically means that you don't have adb in your path. Try running bash```adb``` in the terminal and see what happens. I suspect it won't be able to find it.

**Comment by reddythedev** [comment]
When I run ADB, it prints out it's commands. I have ADB installed and configured properly.

**Comment by Pbatch** [comment]
I've added some more informative debugging. Try again now and post what the new error is :)

**Comment by reddythedev** [comment]
RuntimeError: command '['adb', 'shell', 'wm', 'size']' return with error (code 1): b''

**Comment by reddythedev** [comment]
This happens when I run the adb shell wm size command directly: adb.exe: more than one device/emulator

**Comment by reddythedev** [comment]
Oh, got it to work, thanks tho!
