### ISSUE TITLE
How to run two_six_hog_cycle bot

### ISSUE THREAD

**Issue by emontes22** [Pbatch/ClashRoyaleBuildABot#84]
Hello!
Have any of you guys been able to run the HogCycle bot?
I have everything set up and followed the wiki from top to bottom and everything is working fine.

I can take a screenshot with `python clashroyalebuildabot/screen.py`

and I can run the example bot with `python main.py`

but when I tried to run the HogCycle bot it didn't work nor print to the console.

I've tried running `python two_six_hog_cycle_action.py` and `python two_six_hog_cycle_bot.py` but none of those work and no error gets printed to the console so I don't know what I'm doing wrong. Even the wiki does not explain how to run it so any help would be very much appreciated.

**Comment by nymser** [comment]
i am having this issue as well can you share how u got it to run please
