### ISSUE TITLE
Bounding box

### ISSUE THREAD

**Issue by TheAdroitDBA** [Pbatch/ClashRoyaleBuildABot#85]
I can't seem to get the bounding box to display. I've created main.py files for petebot and tried the example. None of them are displaying. My emulator is set to 720X1280. I've been reading through the code, but haven't been able to find anything on it.

**Comment by TheAdroitDBA** [comment]
I think I found the place I'm supposed to configure it. When you call the but you set debug=True. However, it is still not displaying the bounding box.

I downgraded to python 3.9 and I"m using the following versions of these modules.

flatbuffers==23.5.9
numpy==1.24.3
onnxruntime==1.14.1
pillow 9.5.0
protobuf==4.23.0
scipy==1.10.1

**Comment by TheAdroitDBA** [comment]
I did 2 things and I'm not sure which fixed it. I created a screenshots folder in the source directory. And I updated all of the modules listed above to the ones listed in the requirements. It is now dumping screenshots with the bounding boxes.

**Comment by emontes22** [comment]
would you mind providing the main file for the petebot? I've tried creating it but I had several errors with the card names so maybe I've messed that up and if you can maybe I can find my error. Thank you!

**Comment by emontes22** [comment]
oh, that might be the problem. Do you know which cards are not detected? I've seen the log and zap don't work. I thought it was because those are spells but the fireball works just fine so I don't know why some do not work correctly.

**Comment by Pbatch** [comment]
![image](https://github.com/Pbatch/ClashRoyaleBuildABot/assets/37177749/339c92b1-1222-45c8-b9cd-fb1edbf92dca)

There are the units that are labelled. If any other cards are detected, like the fireball, it's by chance.
