### ISSUE TITLE
new to this sorry

### ISSUE THREAD

**Issue by nymser** [Pbatch/ClashRoyaleBuildABot#88]
![Screenshot (42)](https://github.com/Pbatch/ClashRoyaleBuildABot/assets/136281263/bbe460d0-11a3-4df4-b3bf-ed5fd9c5dfca)
very new to all this trying to get the hog cycle bot what does this mean sorry

discord nymser#4545

C:\Users\12092\AppData\Roaming\Python\Python37\site-packages\clashroyalebuildabot\bot>cd C:\Users\12092\AppData\Roaming\Python\Python37\site-packages\clashroyalebuildabot\bot\two_six_hog_cycle

C:\Users\12092\AppData\Roaming\Python\Python37\site-packages\clashroyalebuildabot\bot\two_six_hog_cycle>python two_six_hog_cycle_bot.py

C:\Users\12092\AppData\Roaming\Python\Python37\site-packages\clashroyalebuildabot\bot\two_six_hog_cycle>python __init__.py
Traceback (most recent call last):
  File "__init__.py", line 2, in <module>
    from .two_six_hog_cycle_bot import TwoSixHogCycle
ImportError: attempted relative import with no known parent package

this is what i get now when i try the bot or action i dont get anything printed out and an import error on init which am i supposed to be using? thank you

do i need to create a main.py?

**Comment by nymser** [comment]
PS C:\Users\12092\AppData\Roaming\Python\Python37\site-packages\clashroyalebuildabot\bot\two_six_hog_cycle> python __init__.py
Traceback (most recent call last):
  File "__init__.py", line 2, in <module>
    from .two_six_hog_cycle_bot import TwoSixHogCycle
ImportError: attempted relative import with no known parent package
PS C:\Users\12092\AppData\Roaming\Python\Python37\site-packages\clashroyalebuildabot\bot\two_six_hog_cycle> python __init__.py
Traceback (most recent call last):
  File "__init__.py", line 2, in <module>
    from .two_six_hog_cycle_bot import TwoSixHogCycle
ImportError: attempted relative import with no known parent package
PS C:\Users\12092\AppData\Roaming\Python\Python37\site-packages\clashroyalebuildabot\bot\two_six_hog_cycle>



kinda lost any help please?

**Comment by nymser** [comment]
am i missing something? like is there more to setup on the petes bot and 26 cycle? think ima tap out head ache haha

**Comment by Pbatch** [comment]
Yes try to run the model as in `example/main.py`; import the Bot class that you're interested in and then run it. You cannot use a bot by running the `.py` file explicitly.
