### ISSUE TITLE
Bot problems... solutions?

### ISSUE THREAD

**Issue by ElSemiJS** [Pbatch/ClashRoyaleBuildABot#91]
Yesterday I was able to perfectly set up the bot, got it to work completely. It played 2-3 Clash Royale matches for me. Suddenly, the game froze during one of those matches and closed. Then I tried to reopen it, but the bot wouldn't work anymore. I tried everything and the only solution I found was to reinstall the game. It started working again with a new account, but once again, after 2-3 matches, the bot stopped working. It could connect fine, but the bot wouldn't click anywhere. And it wouldn't play automatically either. Before, reinstalling Clash Royale used to fix the issue, but now that doesn't work either. (**The problem is that after several matches, the bot seems to stop working and doesn't respond. It doesn't play on its own or do anything, it prints the actions in the console.**)

**Comment by Leviaria** [comment]
I suggest closing this issue as it seems to be a recurring problem from the past. If it resurfaces, please share logs for further investigation. If the issue persists despite our efforts, I'll delve deeper into it. :)
